=== NSSAC/SIMBA_Schelling/schema/Scheduler.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema for the Scheduler.",
    "description": "This schema contains all attributes supported by the Scheduler.",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "name": {
                "type": "string"
            },
            "class": {
                "type": "string"
            },
            "package": {
                "type": "string"
            },
            "priority": {
                "anyOf": [
                    {
                        "type": "number"
                    },
                    {
                        "enum": [
                            "-Infinity",
                            "Infinity"
                        ]
                    }
                ]
            },
            "startTick": {
                "type": "integer",
                "default": 0
            },
            "tickIncrement": {
                "type": "number",
                "minimum": 0,
                "default": 0
            },
            "endTick": {
                "anyOf": [
                    {
                        "type": "integer"
                    },
                    {
                        "enum": [
                            "Infinity"
                        ]
                    }
                ],
                "default": "startTick if tickIncrement is 0, Infinity otherwise"
            },
            "moduleData": {
                "type": "object"
            }
        },
        "required": [
            "name",
            "class",
            "priority"
        ]
    }
}

=== NSSAC/SIMBA_Schelling/reddiego/schedule.json
[
    {
        "name" : "DriverModulePre",
        "class" : "CommandlineModule",
        "package" : "REDDIEGO",
        "priority" : "-Infinity",
        "startTick" : 0,
        "tickIncrement" : 1,
        "moduleData" : {"config" : "DriverModulePre.json"}
    },
    {
        "name" : "DriverModulePost",
        "class" : "CommandlineModule",
        "package" : "REDDIEGO",
        "priority" : "Infinity",
        "startTick" : 0,
        "tickIncrement" : 1,
        "moduleData" : {"config" : "DriverModulePost.json"}
    },
    {
        "name" : "CommandlineModule",
        "class" : "CommandlineModule",
        "package" : "REDDIEGO",
        "priority" : 0,
        "startTick" : 0,
        "tickIncrement" : 1,
        "moduleData" : {"config" : "CommandlineModule.json"}
    }
]
